[package]
name = "ai-strike"
version = "0.1.0"
edition = "2021"
author = "Pal Mezei <sirpalee@gmail.com>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.28.3"